"use client";

import Link from "next/link";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BarChart3, BookOpen, ChevronLeft, ChevronRight, MoreHorizontal, Plus, Search } from "lucide-react";
import { useAcademyBatches } from "@/hooks/use-academy";
import { apiClient, getApiErrorMessage } from "@/services/api";

type Status = "DRAFT" | "IN_REVIEW" | "SCHEDULED" | "UPCOMING" | "LIVE" | "EXPIRED" | "CLOSED" | "ARCHIVED";
type ControlExam = { id: string; title: string; subject?: string | null; topic?: string | null; lifecycle: string; displayStatus: Status; resumeStage: string; examStartsAt?: string | null; examEndsAt?: string | null; batch?: { name: string } | null; teacher?: { name: string } | null };
type Response = { tests: ControlExam[]; kpis: { drafts: number; scheduled: number; live: number }; pagination: { page: number; total: number; pages: number; limit: number } };
const statuses: Array<{ value: string; label: string }> = [{ value: "", label: "All statuses" }, ...["DRAFT", "IN_REVIEW", "SCHEDULED", "UPCOMING", "LIVE", "EXPIRED", "CLOSED", "ARCHIVED"].map((value) => ({ value, label: value.replace("_", " ") }))];
const pill: Record<Status, string> = { DRAFT: "bg-stone-100 text-stone-700", IN_REVIEW: "bg-amber-50 text-amber-800", SCHEDULED: "bg-blue-50 text-blue-800", UPCOMING: "bg-sky-50 text-sky-800", LIVE: "bg-emerald-50 text-emerald-800", EXPIRED: "bg-slate-100 text-slate-600", CLOSED: "bg-slate-200 text-slate-800", ARCHIVED: "bg-stone-100 text-stone-500" };

function dateParts(test: ControlExam) {
  if (!test.examStartsAt || !test.examEndsAt) return { date: "—", time: "Window not set" };
  const options = { timeZone: "Asia/Kolkata" } as const;
  return { date: new Date(test.examStartsAt).toLocaleDateString("en-IN", { ...options, day: "numeric", month: "short", year: "numeric" }), time: `${new Date(test.examStartsAt).toLocaleTimeString("en-IN", { ...options, hour: "numeric", minute: "2-digit" })} – ${new Date(test.examEndsAt).toLocaleTimeString("en-IN", { ...options, hour: "numeric", minute: "2-digit" })}` };
}

export function DirectorExamControl() {
  const queryClient = useQueryClient(); const { data: batches = [] } = useAcademyBatches({}, true);
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [batchId, setBatchId] = useState(""); const [page, setPage] = useState(1);
  const query = useQuery({ queryKey: ["tests", "control", search, status, batchId, page], queryFn: async () => (await apiClient.get<Response>("/tests/control", { params: { search: search || undefined, status: status || undefined, batchId: batchId || undefined, page, limit: 10 } })).data });
  const transition = useMutation({ mutationFn: ({ id, lifecycle }: { id: string; lifecycle: string }) => apiClient.patch(`/tests/${id}/lifecycle`, { lifecycle }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["tests", "control"] }) });
  const clear = () => { setSearch(""); setStatus(""); setBatchId(""); setPage(1); };
  return <main className="mx-auto max-w-7xl px-4 py-8 text-slate-950 md:px-8">
    <header className="border-b border-stone-200 pb-5"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#0b5d8f]">NIDUS AI Exams</p><h1 className="mt-2 text-3xl font-bold">Exam Control</h1><p className="mt-1 text-sm text-slate-500">Create, monitor and manage academy examinations.</p></header>
    <section aria-label="Exam status summary" className="mt-5 grid grid-cols-3 overflow-hidden rounded-xl border border-stone-200 bg-white shadow-sm">
      {[["Drafts", query.data?.kpis.drafts ?? 0, "DRAFT"], ["Scheduled", query.data?.kpis.scheduled ?? 0, "SCHEDULED"], ["Live", query.data?.kpis.live ?? 0, "LIVE"]].map(([label, value, target], index) => <button key={label} type="button" onClick={() => { setStatus(String(target)); setPage(1); }} className={`p-4 text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#0b5d8f] ${index ? "border-l border-stone-200" : ""}`}><span className="block text-xs font-bold uppercase tracking-wide text-slate-500">{label}</span><span className="mt-1 block text-2xl font-bold text-[#0b3558]">{value}</span></button>)}
    </section>
    <nav aria-label="Exam actions" className="mt-5 flex flex-wrap gap-2"><Link href="/dashboard/director/exams?create=1" className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#0b3558] px-4 text-sm font-bold text-white"><Plus size={16}/> Create Exam</Link><Link href="/examination-center/question-bank" className="inline-flex h-10 items-center gap-2 rounded-lg border border-stone-300 bg-white px-4 text-sm font-bold"><BookOpen size={16}/> Question Bank</Link><Link href="/examination-center/results" className="inline-flex h-10 items-center gap-2 rounded-lg border border-stone-300 bg-white px-4 text-sm font-bold"><BarChart3 size={16}/> Results</Link></nav>
    <section aria-label="Exam filters" className="mt-5 grid gap-3 rounded-xl border border-stone-200 bg-white p-3 shadow-sm md:grid-cols-[1fr_190px_220px_auto]"><label className="relative"><span className="sr-only">Search exams</span><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search exams..." className="h-10 w-full rounded-lg border border-stone-300 pl-9 pr-3 text-sm"/></label><label><span className="sr-only">Status</span><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} className="h-10 w-full rounded-lg border border-stone-300 bg-white px-3 text-sm">{statuses.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label><span className="sr-only">Batch</span><select value={batchId} onChange={(e) => { setBatchId(e.target.value); setPage(1); }} className="h-10 w-full rounded-lg border border-stone-300 bg-white px-3 text-sm"><option value="">All batches</option>{batches.map((batch) => <option key={batch.id} value={batch.id}>{batch.name}</option>)}</select></label><button type="button" onClick={clear} className="h-10 rounded-lg px-3 text-sm font-bold text-[#0b5d8f]">Clear filters</button></section>
    {query.isLoading ? <p className="mt-6 rounded-xl border bg-white p-8 text-center text-sm">Loading exams…</p> : query.isError ? <div role="alert" className="mt-6 rounded-xl border bg-white p-8 text-center"><p>Unable to load exams.</p><button onClick={() => query.refetch()} className="mt-3 font-bold text-[#0b5d8f]">Retry</button></div> : query.data?.tests.length ? <>
      <div className="mt-5 hidden overflow-visible rounded-xl border border-stone-200 bg-white shadow-sm md:block"><table className="w-full text-left text-sm"><thead className="bg-[#fbf8f1] text-xs uppercase tracking-wide text-slate-500"><tr>{["Exam / Subject", "Batch", "Owner", "Examination", "Status", "Actions"].map((label) => <th key={label} scope="col" className="px-4 py-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-stone-200">{query.data.tests.map((test) => <ExamRow key={test.id} test={test} transition={(lifecycle) => transition.mutate({ id: test.id, lifecycle })}/>)}</tbody></table></div>
      <ul className="mt-5 grid gap-3 md:hidden">{query.data.tests.map((test) => <MobileExam key={test.id} test={test} transition={(lifecycle) => transition.mutate({ id: test.id, lifecycle })}/>)}</ul>
      <footer className="mt-4 flex items-center justify-between text-sm text-slate-600"><span>Showing {(page - 1) * 10 + 1}–{Math.min(page * 10, query.data.pagination.total)} of {query.data.pagination.total}</span><div className="flex gap-2"><button aria-label="Previous page" disabled={page <= 1} onClick={() => setPage((p) => p - 1)} className="rounded-lg border bg-white p-2 disabled:opacity-40"><ChevronLeft size={16}/></button><button aria-label="Next page" disabled={page >= query.data.pagination.pages} onClick={() => setPage((p) => p + 1)} className="rounded-lg border bg-white p-2 disabled:opacity-40"><ChevronRight size={16}/></button></div></footer>
    </> : <div className="mt-6 rounded-xl border border-stone-200 bg-white p-10 text-center shadow-sm"><h2 className="font-bold">{search || status || batchId ? "No exams match these filters." : "No exams yet."}</h2><p className="mt-1 text-sm text-slate-500">{search || status || batchId ? "Try clearing one or more filters." : "Create your first exam to get started."}</p>{search || status || batchId ? <button onClick={clear} className="mt-4 font-bold text-[#0b5d8f]">Clear filters</button> : <Link href="/dashboard/director/exams?create=1" className="mt-4 inline-flex rounded-lg bg-[#0b3558] px-4 py-2 text-sm font-bold text-white">Create Exam</Link>}</div>}
    {transition.isError ? <p role="alert" className="mt-3 text-sm text-red-700">{getApiErrorMessage(transition.error)}</p> : null}
  </main>;
}

function actions(test: ControlExam, transition: (lifecycle: string) => void) { const items: React.ReactNode[] = [<Link key="view" href={`/tests/${test.id}`} className="block px-3 py-2 hover:bg-stone-50">View</Link>]; if (test.displayStatus === "DRAFT") items.push(<Link key="edit" href={`/dashboard/director/exams?resume=${test.id}&stage=${test.resumeStage}`} className="block px-3 py-2 hover:bg-stone-50">Continue Editing</Link>); if (test.displayStatus === "IN_REVIEW" || test.displayStatus === "SCHEDULED") items.push(<button key="draft" type="button" onClick={() => transition("DRAFT")} className="block w-full px-3 py-2 text-left hover:bg-stone-50">{test.displayStatus === "SCHEDULED" ? "Cancel Schedule" : "Return to Draft"}</button>); if (["LIVE", "UPCOMING", "EXPIRED"].includes(test.displayStatus)) { items.push(<Link key="results" href={`/examination-center/results?testId=${test.id}`} className="block px-3 py-2 hover:bg-stone-50">Results</Link>); items.push(<button key="close" type="button" onClick={() => transition("CLOSED")} className="block w-full px-3 py-2 text-left hover:bg-stone-50">Close Exam</button>); } if (["CLOSED", "ARCHIVED"].includes(test.displayStatus)) items.push(<Link key="results2" href={`/examination-center/results?testId=${test.id}`} className="block px-3 py-2 hover:bg-stone-50">Results</Link>); if (test.displayStatus === "CLOSED") items.push(<button key="archive" type="button" onClick={() => transition("ARCHIVED")} className="block w-full px-3 py-2 text-left hover:bg-stone-50">Archive</button>); return items; }
function Menu({ test, transition }: { test: ControlExam; transition: (lifecycle: string) => void }) { return <details className="relative"><summary aria-label={`Actions for ${test.title}`} className="list-none cursor-pointer rounded-lg border p-2"><MoreHorizontal size={16}/></summary><div className="absolute right-0 z-20 mt-1 min-w-40 rounded-lg border border-stone-200 bg-white py-1 text-sm shadow-lg">{actions(test, transition)}</div></details>; }
function ExamRow({ test, transition }: { test: ControlExam; transition: (lifecycle: string) => void }) { const when = dateParts(test); return <tr><td className="px-4 py-4"><p className="font-bold">{test.title}</p><p className="text-xs text-slate-500">{test.subject || "—"}{test.topic ? ` • ${test.topic}` : ""}</p></td><td className="px-4 py-4">{test.batch?.name || "—"}</td><td className="px-4 py-4">{test.teacher?.name || "—"}</td><td className="px-4 py-4"><p>{when.date}</p><p className="text-xs text-slate-500">{when.time}</p></td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${pill[test.displayStatus]}`}>{test.displayStatus.replace("_", " ")}</span></td><td className="px-4 py-4"><Menu test={test} transition={transition}/></td></tr>; }
function MobileExam({ test, transition }: { test: ControlExam; transition: (lifecycle: string) => void }) { const when = dateParts(test); return <li className="rounded-xl border border-stone-200 bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><div><h2 className="font-bold">{test.title}</h2><p className="text-xs text-slate-500">{test.subject || "—"}{test.topic ? ` • ${test.topic}` : ""}</p></div><Menu test={test} transition={transition}/></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-slate-500">Batch</dt><dd>{test.batch?.name || "—"}</dd></div><div><dt className="text-xs text-slate-500">Owner</dt><dd>{test.teacher?.name || "—"}</dd></div><div><dt className="text-xs text-slate-500">Examination</dt><dd>{when.date}<br/>{when.time}</dd></div><div><dt className="text-xs text-slate-500">Status</dt><dd className="mt-1"><span className={`rounded-full px-2 py-1 text-xs font-bold ${pill[test.displayStatus]}`}>{test.displayStatus.replace("_", " ")}</span></dd></div></dl></li>; }
