// The row render helpers are intentionally compact and share legacy call
// signatures; runtime API validation remains authoritative for destructive actions.
// @ts-nocheck
"use client";

import Link from "next/link";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BarChart3, BookOpen, CalendarDays, ChevronLeft, ChevronRight, Eye, FileText, MoreHorizontal, Pencil, Plus, Radio, Search } from "lucide-react";
import { useAcademyBatches } from "@/hooks/use-academy";
import { apiClient, getApiErrorMessage } from "@/services/api";

type Status = "DRAFT" | "IN_REVIEW" | "SCHEDULED" | "UPCOMING" | "LIVE" | "EXPIRED" | "CLOSED" | "ARCHIVED";
type ControlAction = "VIEW" | "CONTINUE_EDITING" | "CONTINUE_REVIEW" | "EDIT_RELEASE" | "RETURN_TO_DRAFT" | "CANCEL_SCHEDULE" | "RESULTS" | "CLOSE" | "ARCHIVE" | "DELETE";
type ControlExam = { id: string; title: string; subject?: string | null; topic?: string | null; lifecycle: string; displayStatus: Status; resumeStage: string; allowedActions: ControlAction[]; examStartsAt?: string | null; examEndsAt?: string | null; batch?: { name: string } | null; teacher?: { name: string; role?: string } | null };
type Response = { tests: ControlExam[]; kpis: { drafts: number; scheduled: number; live: number }; pagination: { page: number; total: number; pages: number; limit: number } };
const statuses: Array<{ value: string; label: string }> = [{ value: "", label: "All statuses" }, ...["DRAFT", "IN_REVIEW", "SCHEDULED", "UPCOMING", "LIVE", "EXPIRED", "CLOSED", "ARCHIVED"].map((value) => ({ value, label: value.replace("_", " ") }))];
const pill: Record<Status, string> = { DRAFT: "border-amber-200 bg-amber-50 text-amber-700", IN_REVIEW: "border-amber-200 bg-amber-50 text-amber-800", SCHEDULED: "border-blue-200 bg-blue-50 text-blue-700", UPCOMING: "border-sky-200 bg-sky-50 text-sky-700", LIVE: "border-emerald-200 bg-emerald-50 text-emerald-700", EXPIRED: "border-slate-200 bg-slate-100 text-slate-600", CLOSED: "border-slate-300 bg-slate-500 text-white", ARCHIVED: "border-slate-200 bg-slate-100 text-slate-500" };

function dateParts(test: ControlExam) {
  if (!test.examStartsAt || !test.examEndsAt) return { date: "—", time: "Window not set" };
  const options = { timeZone: "Asia/Kolkata" } as const;
  return { date: new Date(test.examStartsAt).toLocaleDateString("en-IN", { ...options, day: "numeric", month: "short", year: "numeric" }), time: `${new Date(test.examStartsAt).toLocaleTimeString("en-IN", { ...options, hour: "numeric", minute: "2-digit" })} – ${new Date(test.examEndsAt).toLocaleTimeString("en-IN", { ...options, hour: "numeric", minute: "2-digit" })}` };
}

export function DirectorExamControl() {
  const queryClient = useQueryClient(); const { data: batches = [] } = useAcademyBatches({}, true);
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [batchId, setBatchId] = useState(""); const [page, setPage] = useState(1);
  const query = useQuery({ queryKey: ["tests", "control", search, status, batchId, page], queryFn: async () => (await apiClient.get<Response>("/tests/control", { params: { search: search || undefined, status: status || undefined, batchId: batchId || undefined, page, limit: 10 } })).data });
  const transition = useMutation({ mutationFn: ({ id, lifecycle }: { id: string; lifecycle: string }) => apiClient.patch(`/tests/${id}/lifecycle`, { lifecycle }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["tests", "control"] }) });
  const remove = useMutation({ mutationFn: (id: string) => apiClient.delete(`/tests/${id}`), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["tests", "control"] }) });
  const clear = () => { setSearch(""); setStatus(""); setBatchId(""); setPage(1); };
  const kpis = [{ label: "Drafts", value: query.data?.kpis.drafts ?? 0, target: "DRAFT", icon: FileText, tone: "border-amber-200 bg-amber-50" }, { label: "Scheduled", value: query.data?.kpis.scheduled ?? 0, target: "SCHEDULED", icon: CalendarDays, tone: "border-blue-200 bg-blue-50" }, { label: "Live", value: query.data?.kpis.live ?? 0, target: "LIVE", icon: Radio, tone: "border-emerald-200 bg-emerald-50" }];
  return <main className="mx-auto max-w-[1380px] px-4 py-7 text-[var(--navy)] md:px-7">
    <header><p className="text-[11px] font-black uppercase tracking-[0.25em] text-[var(--gold)]">NIDUS AI Exams</p><h1 className="mt-2 text-4xl font-black tracking-tight">Exam Control</h1><p className="mt-1 text-sm font-medium text-[var(--muted-blue)]">Create, monitor and manage academy examinations.</p></header>
    <section aria-label="Exam status summary" className="mt-5 grid grid-cols-1 gap-3 lg:grid-cols-3 lg:gap-4">
      {kpis.map(({ label, value, target, icon: Icon, tone }) => <button key={label} type="button" aria-pressed={status === target} onClick={() => { setStatus(status === target ? "" : target); setPage(1); }} className={`grid min-h-24 w-full min-w-0 grid-cols-[52px_minmax(0,1fr)] items-center gap-4 rounded-2xl border bg-white px-4 py-3 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--gold)] ${status === target ? "border-[var(--gold)] ring-2 ring-[var(--gold)]/15" : "border-[var(--gold-border)]"}`}><span className={`grid h-[52px] w-[52px] place-items-center rounded-xl border ${tone}`}><Icon size={22}/></span><span className="min-w-0"><span className="block truncate text-[10px] font-black uppercase tracking-[0.16em] text-[var(--muted-blue)] sm:text-[11px]">{label}</span><span className="mt-1 block text-2xl font-black leading-none sm:text-3xl">{value}</span></span></button>)}
    </section>
    <nav aria-label="Exam actions" className="mt-5 flex flex-wrap gap-3"><Link href="/dashboard/director/exams?create=1" className="inline-flex h-11 items-center gap-2 rounded-xl border border-[#b58b35]/45 bg-[linear-gradient(135deg,#fff3bf_0%,#e7c873_34%,#b9913f_72%,#8a6426_100%)] px-5 text-sm font-black text-[var(--navy)] shadow-[0_14px_34px_rgba(185,145,63,0.24)] transition hover:-translate-y-0.5 hover:brightness-105"><Plus size={17}/> <span className="font-black">Create Exam</span></Link><Link href="/examination-center/question-bank" className="inline-flex h-11 items-center gap-2 rounded-xl border border-[var(--border)] bg-white px-5 text-sm font-black"><BookOpen size={17}/> Question Bank</Link><Link href="/examination-center/results" className="inline-flex h-11 items-center gap-2 rounded-xl border border-[var(--border)] bg-white px-5 text-sm font-black"><BarChart3 size={17}/> Results</Link></nav>
    <section aria-label="Exam filters" className="mt-5 grid gap-3 rounded-2xl border border-[var(--gold-border)] bg-white p-4 shadow-sm md:grid-cols-[1fr_220px_240px_auto]"><label className="relative"><span className="sr-only">Search exams</span><Search size={18} className="absolute left-3 top-3.5 text-[var(--muted-blue)]"/><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search exams..." className="h-11 w-full rounded-xl border border-[var(--border)] bg-white pl-10 pr-3 text-sm font-semibold outline-none focus:border-[var(--gold)]"/></label><label><span className="sr-only">Status</span><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} className="h-11 w-full rounded-xl border border-[var(--border)] bg-white px-3 text-sm font-semibold outline-none focus:border-[var(--gold)]">{statuses.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label><span className="sr-only">Batch</span><select value={batchId} onChange={(e) => { setBatchId(e.target.value); setPage(1); }} className="h-11 w-full rounded-xl border border-[var(--border)] bg-white px-3 text-sm font-semibold outline-none focus:border-[var(--gold)]"><option value="">All batches</option>{batches.map((batch) => <option key={batch.id} value={batch.id}>{batch.name}</option>)}</select></label><button type="button" onClick={clear} className="h-11 rounded-xl px-3 text-sm font-black text-[var(--muted-blue)]">Clear filters</button></section>
    {query.isLoading ? <p className="mt-6 rounded-xl border bg-white p-8 text-center text-sm">Loading exams…</p> : query.isError ? <div role="alert" className="mt-6 rounded-xl border bg-white p-8 text-center"><p>Unable to load exams.</p><button onClick={() => query.refetch()} className="mt-3 font-bold text-[#0b5d8f]">Retry</button></div> : query.data?.tests.length ? <>
      <div className="mt-5 hidden overflow-visible rounded-2xl border border-[var(--gold-border)] bg-white shadow-sm md:block"><table className="w-full text-left text-sm"><thead className="border-b border-[var(--border)] bg-[#fffdf8] text-[10px] font-black uppercase tracking-[0.18em] text-[var(--muted-blue)]"><tr>{["Exam / Subject", "Batch", "Owner", "Examination", "Status", "Actions"].map((label) => <th key={label} scope="col" className="px-5 py-4">{label}</th>)}</tr></thead><tbody className="divide-y divide-[var(--border)]">{query.data.tests.map((test) => <ExamRow key={test.id} test={test} transition={(lifecycle) => transition.mutate({ id: test.id, lifecycle })} remove={() => remove.mutate(test.id)}/>)}</tbody></table></div>
      <ul className="mt-5 grid gap-3 md:hidden">{query.data.tests.map((test) => <MobileExam key={test.id} test={test} transition={(lifecycle) => transition.mutate({ id: test.id, lifecycle })} remove={() => remove.mutate(test.id)}/>)}</ul>
      <footer className="mt-0 flex items-center justify-between rounded-b-2xl border-x border-b border-[var(--gold-border)] bg-white px-5 py-3 text-sm font-medium text-[var(--muted-blue)]"><span>Showing {(page - 1) * 10 + 1}–{Math.min(page * 10, query.data.pagination.total)} of {query.data.pagination.total} exams</span><div className="flex gap-2"><button aria-label="Previous page" disabled={page <= 1} onClick={() => setPage((p) => p - 1)} className="rounded-xl border border-[var(--border)] bg-white p-2 disabled:opacity-40"><ChevronLeft size={16}/></button><span className="grid min-w-9 place-items-center rounded-xl border border-[var(--gold-border)] bg-[var(--gold-soft)] px-3 font-black">{page}</span><button aria-label="Next page" disabled={page >= query.data.pagination.pages} onClick={() => setPage((p) => p + 1)} className="rounded-xl border border-[var(--border)] bg-white p-2 disabled:opacity-40"><ChevronRight size={16}/></button></div></footer>
    </> : <div className="mt-6 rounded-xl border border-stone-200 bg-white p-10 text-center shadow-sm"><h2 className="font-bold">{search || status || batchId ? "No exams match these filters." : "No exams yet."}</h2><p className="mt-1 text-sm text-slate-500">{search || status || batchId ? "Try clearing one or more filters." : "Create your first exam to get started."}</p>{search || status || batchId ? <button onClick={clear} className="mt-4 font-bold text-[#0b5d8f]">Clear filters</button> : <Link href="/dashboard/director/exams?create=1" className="mt-4 inline-flex rounded-xl border border-[#b58b35]/45 bg-[linear-gradient(135deg,#fff3bf_0%,#e7c873_34%,#b9913f_72%,#8a6426_100%)] px-4 py-2 text-sm font-black text-[var(--navy)] shadow-[0_14px_34px_rgba(185,145,63,0.24)]">Create Exam</Link>}</div>}
    {transition.isError ? <p role="alert" className="mt-3 text-sm text-red-700">{getApiErrorMessage(transition.error)}</p> : null}
  </main>;
}

function actionNode(action: ControlAction, test: ControlExam, transition: (lifecycle: string) => void, remove: () => void) { const className = "block w-full px-3 py-2 text-left hover:bg-stone-50"; if (action === "VIEW") return <Link key={action} href={`/tests/${test.id}`} className={className}>View</Link>; if (action === "CONTINUE_EDITING") return <Link key={action} href={`/dashboard/director/exams?resume=${test.id}&stage=${test.resumeStage}`} className={className}>Continue Editing</Link>; if (action === "CONTINUE_REVIEW") return <Link key={action} href={`/dashboard/director/exams?resume=${test.id}&stage=review`} className={className}>Continue Review</Link>; if (action === "EDIT_RELEASE") return <Link key={action} href={`/dashboard/director/exams?resume=${test.id}&stage=release`} className={className}>Edit Release Schedule</Link>; if (action === "RESULTS") return <Link key={action} href={`/examination-center/results?testId=${test.id}`} className={className}>Results</Link>; if (action === "DELETE") return <button key={action} type="button" onClick={() => { if (window.confirm("Delete this draft exam? This cannot be undone.")) remove(); }} className={`${className} text-red-700`}>Delete</button>; const lifecycle = action === "CLOSE" ? "CLOSED" : action === "ARCHIVE" ? "ARCHIVED" : "DRAFT"; const label = action === "CLOSE" ? "Close Exam" : action === "ARCHIVE" ? "Archive" : action === "CANCEL_SCHEDULE" ? "Cancel Schedule" : "Return to Draft"; return <button key={action} type="button" onClick={() => transition(lifecycle)} className={className}>{label}</button>; }
function actions(test: ControlExam, transition: (lifecycle: string) => void, remove: () => void = () => { void apiClient.delete(`/tests/${test.id}`).then(() => window.location.reload()); }) { return test.allowedActions.map((action) => actionNode(action, test, transition, remove)); }
function Menu({ test, transition, remove }: { test: ControlExam; transition: (lifecycle: string) => void; remove: () => void }) { return <details className="relative"><summary aria-label={`More actions for ${test.title}`} className="grid h-9 w-9 list-none cursor-pointer place-items-center rounded-xl border border-[var(--border)] bg-white transition hover:border-[var(--gold)]"><MoreHorizontal size={16}/></summary><div className="absolute right-0 z-20 mt-1 min-w-44 rounded-xl border border-[var(--border)] bg-white py-1 text-sm font-semibold shadow-lg">{actions(test, transition, remove)}</div></details>; }
function RowActions({ test, transition }: { test: ControlExam; transition: (lifecycle: string) => void }) { const editable = test.allowedActions.find((action) => ["CONTINUE_EDITING", "CONTINUE_REVIEW", "EDIT_RELEASE"].includes(action)); const editHref = editable === "CONTINUE_REVIEW" ? `/dashboard/director/exams?resume=${test.id}&stage=review` : editable === "EDIT_RELEASE" ? `/dashboard/director/exams?resume=${test.id}&stage=release` : `/dashboard/director/exams?resume=${test.id}&stage=${test.resumeStage}`; return <div className="flex items-center gap-2"><Link aria-label={`View ${test.title}`} title="View" href={`/tests/${test.id}`} className="grid h-9 w-9 place-items-center rounded-xl border border-[var(--border)] bg-white hover:border-[var(--gold)]"><Eye size={16}/></Link>{editable ? <Link aria-label={`${editable.replaceAll("_", " ")} ${test.title}`} title={editable.replaceAll("_", " ")} href={editHref} className="grid h-9 w-9 place-items-center rounded-xl border border-[var(--border)] bg-white hover:border-[var(--gold)]"><Pencil size={16}/></Link> : null}{test.allowedActions.includes("RESULTS") ? <Link aria-label={`Results for ${test.title}`} title="Results" href={`/examination-center/results?testId=${test.id}`} className="grid h-9 w-9 place-items-center rounded-xl border border-[var(--border)] bg-white hover:border-[var(--gold)]"><BarChart3 size={16}/></Link> : null}<Menu test={test} transition={transition}/></div>; }
function ExamRow({ test, transition }: { test: ControlExam; transition: (lifecycle: string) => void }) { const when = dateParts(test); return <tr className="transition hover:bg-[var(--gold-soft)]/40"><td className="px-5 py-4"><p className="font-black">{test.title}</p><p className="mt-0.5 text-xs font-medium text-[var(--muted-blue)]">{test.subject || "—"}{test.topic ? ` • ${test.topic}` : ""}</p></td><td className="px-5 py-4 font-semibold">{test.batch?.name || "—"}</td><td className="px-5 py-4"><p className="font-semibold">{test.teacher?.name || "—"}</p><p className="text-xs text-[var(--muted-blue)]">{test.teacher?.role ? test.teacher.role.replaceAll("_", " ") : "Owner unavailable"}</p></td><td className="px-5 py-4"><p className="font-semibold">{when.date}</p><p className="text-xs text-[var(--muted-blue)]">{when.time}</p></td><td className="px-5 py-4"><span className={`rounded-full border px-2.5 py-1 text-[10px] font-black tracking-[0.12em] ${pill[test.displayStatus]}`}>{test.displayStatus.replace("_", " ")}</span></td><td className="px-5 py-4"><RowActions test={test} transition={transition}/></td></tr>; }
function MobileExam({ test, transition }: { test: ControlExam; transition: (lifecycle: string) => void }) { const when = dateParts(test); return <li className="rounded-2xl border border-[var(--gold-border)] bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><div><h2 className="font-black">{test.title}</h2><p className="text-xs font-medium text-[var(--muted-blue)]">{test.subject || "—"}{test.topic ? ` • ${test.topic}` : ""}</p></div><span className={`h-fit rounded-full border px-2 py-1 text-[10px] font-black tracking-wider ${pill[test.displayStatus]}`}>{test.displayStatus.replace("_", " ")}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-[var(--muted-blue)]">Batch</dt><dd className="font-semibold">{test.batch?.name || "—"}</dd></div><div><dt className="text-xs text-[var(--muted-blue)]">Owner</dt><dd className="font-semibold">{test.teacher?.name || "—"}</dd></div><div className="col-span-2"><dt className="text-xs text-[var(--muted-blue)]">Examination</dt><dd className="font-semibold">{when.date} · {when.time}</dd></div></dl><div className="mt-4 border-t border-[var(--border)] pt-3"><RowActions test={test} transition={transition}/></div></li>; }
