ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ACADEMIC_HEAD';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'PHYSICAL_TRAINER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ADMINISTRATIVE_OFFICER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'BUSINESS_DEVELOPMENT_EXECUTIVE';
